package model

const KeyGroupId = "X-Awakari-Group-Id"
const KeyUserId = "X-Awakari-User-Id"

const CeKeyTgFileId = "tgfileid"
const CeKeyTgFileUniqueId = "tgfileuniqueid"
const CeKeyTgFileMediaDuration = "tgfilemediaduration"
const CeKeyTgFileImgHeight = "tgfileimgheight"
const CeKeyTgFileImgWidth = "tgfileimgwidth"
const CeKeyTgFileType = "tgfiletype"
const CeKeyLatitude = "latitude"
const CeKeyLongitude = "longitude"
const CeKeyTime = "time"
const CeKeyCategories = "categories"
const CeKeySnippet = "snippet"
const CeKeyName = "name"
const CeKeyDescription = "description"
const CeKeyTitle = "title"
const CeKeySummary = "summary"
const CeKeyHeadline = "headline"
