# prod
cert:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
  issuer:
    name: letsencrypt

ingress:
  hosts:
    - host: tgbot.awakari.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-bot-telegram-tls-server
      hosts:
        - tgbot.awakari.com

api:
  usage:
    limits:
      interestsPublic: "-1002258438008:1"
      interests: "-1002666141766:5,-1002579740404:10"
      subscriptions: "-1002672306001:10,-1002582439931:20"
