api:
  messages:
    uri: "messages:50051"
  writer:
    uri: "resolver:50051"
ingress:
  hosts:
    - host: tgbot.awakari.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-bot-telegram-tls-server
      hosts:
        - tgbot.awakari.com
