api:
  messages:
    uri: "messages:50051"
  writer:
    uri: "resolver:50051"

# prod
cert:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
  issuer:
    name: letsencrypt

ingress:
  hosts:
    - host: tgbot.awakari.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-bot-telegram-tls-server
      hosts:
        - tgbot.awakari.com
