ingress:
  hosts:
    - host: demo.tgbot.awakari.cloud
      paths:
        - path: /webhook
          pathType: ImplementationSpecific
  tls:
    - secretName: secret-api-tls-server
      hosts:
        - demo.tgbot.awakari.cloud
