apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bot-telegram.fullname" . }}
  labels:
    {{- include "bot-telegram.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bot-telegram.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bot-telegram.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bot-telegram.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: "{{ .Values.priority.class }}"
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_MESSAGES_TYPE
              value: "{{ .Values.api.messages.type }}"
            - name: API_READER_URI
              value: "{{ .Values.api.reader.uri }}"
            - name: API_READER_URI_EVT_BASE
              value: "{{ .Values.api.reader.uriEvtBase }}"
            - name: API_READER_CALLBACK_PROTOCOL
              value: "{{ .Values.api.reader.callback.protocol }}"
            - name: API_READER_CALLBACK_HOST
              value: "{{ include "bot-telegram.fullname" . }}"
            - name: API_READER_CALLBACK_PORT
              value: "{{ .Values.service.callback.port }}"
            - name: API_READER_CALLBACK_PATH
              value: "{{ .Values.api.reader.callback.path }}"
            {{- range .Values.ingress.hosts }}
            - name: API_TELEGRAM_WEBHOOK_HOST
              value: {{ .host }}
            {{- range .paths }}
            - name: API_TELEGRAM_WEBHOOK_PATH
              value: {{ .path }}
            {{- end }}
            {{- end }}
            - name: API_TELEGRAM_BOT_PORT
              value: "{{ .Values.service.grpc.port }}"
            - name: API_TELEGRAM_WEBHOOK_PORT
              value: "{{ .Values.service.port }}"
            - name: API_TELEGRAM_WEBHOOK_CONN_MAX
              value: "{{ .Values.api.telegram.webhook.connections.max }}"
            - name: API_TELEGRAM_WEBHOOK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bot-telegram.fullname" . }}"
                  key: webhookToken
            - name: API_TELEGRAM_SUPPORT_CHAT_ID
              valueFrom:
                secretKeyRef:
                  key: support
                  name: "{{ include "bot-telegram.fullname" . }}"
            - name: API_TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bot-telegram.fullname" . }}"
                  key: telegram
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
            - name: API_QUEUE_URI
              value: "{{ .Values.api.queue.uri }}"
            - name: API_QUEUE_INTERESTS_CREATED_BATCH_SIZE
              value: "{{ .Values.api.queue.interestsCreated.batchSize }}"
            - name: API_QUEUE_INTERESTS_CREATED_NAME
              value: "{{ .Values.api.queue.interestsCreated.name }}"
            - name: API_QUEUE_INTERESTS_CREATED_SUBJ
              value: "{{ .Values.api.queue.interestsCreated.subj }}"
            - name: API_WRITER_URI
              value: "{{ .Values.api.writer.uri }}"
            - name: API_INTERESTS_URI
              value: "{{ .Values.api.interests.uri }}"
            - name: API_TOKEN_INTERNAL
              valueFrom:
                secretKeyRef:
                  key: "{{ .Values.api.token.internal.key }}"
                  name: "{{ .Values.api.token.internal.name }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpc.port }}
            - name: callback
              containerPort: {{ .Values.service.callback.port }}
          livenessProbe:
            grpc:
              port: {{ .Values.service.grpc.port }}
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "bot-telegram.name" . }}
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
