kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: bot-telegram-allow-internet
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app: bot-telegram
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
