{{- $fullName := include "bot-telegram.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ .Values.cert.issuer.name }}-bot-telegram"
spec:
  acme:
    server: {{ .Values.cert.acme.server }}
    email: {{ .Values.cert.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.cert.issuer.name }}
    solvers:
      - http01:
          ingress:
            name: "{{ $fullName }}"
