{{- if .Values.ingress.tls }}
{{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""
{{- end }}
{{- end }}
