apiVersion: v1
kind: Service
metadata:
  name: {{ include "bot-telegram.fullname" . }}
  labels:
    {{- include "bot-telegram.labels" . | nindent 4 }}
  annotations: {}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.callback.port }}
      targetPort: callback
      protocol: TCP
      name: callback
  selector:
    {{- include "bot-telegram.selectorLabels" . | nindent 4 }}
