apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bot-telegram.fullname" . }}
  labels:
    {{- include "bot-telegram.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bot-telegram.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bot-telegram.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bot-telegram.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_URI
              value: "{{ .Values.api.uri }}"
            - name: API_ADMIN_URI
              value: "{{ .Values.api.admin.uri }}"
            - name: API_MESSAGES_URI
              value: "{{ .Values.api.messages.uri }}"
            - name: API_WRITER_URI
              value: "{{ .Values.api.writer.uri }}"
            {{- range .Values.ingress.hosts }}
            - name: API_TELEGRAM_WEBHOOK_HOST
              value: {{ .host }}
            {{- range .paths }}
            - name: API_TELEGRAM_WEBHOOK_PATH
              value: {{ .path }}
            {{- end }}
            {{- end }}
            - name: API_TELEGRAM_WEBHOOK_PORT
              value: "{{ .Values.service.port }}"
            - name: API_TELEGRAM_WEBHOOK_CONN_MAX
              value: "{{ .Values.api.telegram.webhook.connections.max }}"
            - name: API_TELEGRAM_WEBHOOK_TOKEN
              value: "{{ .Values.api.telegram.webhook.token }}"
            - name: API_TELEGRAM_SUPPORT_CHAT_ID
              value: "{{ .Values.api.telegram.support.chat.id }}"
            - name: API_TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bot-telegram.fullname" . }}-tokens"
                  key: telegram
            - name: API_SOURCE_FEEDS_URI
              value: "{{ .Values.api.source.feeds.uri }}"
            - name: API_SOURCE_SITES_URI
              value: "{{ .Values.api.source.sites.uri }}"
            - name: API_SOURCE_TELEGRAM_URI
              value: "{{ .Values.api.source.telegram.uri }}"
            - name: CHATS_DB_URI
              value: "{{ .Values.chats.db.protocol }}://{{ .Values.chats.db.hostname }}/?retryWrites=true&w=majority"
            - name: CHATS_DB_NAME
              value: {{ .Values.chats.db.name }}
            - name: CHATS_DB_USERNAME
              value: {{ .Values.chats.db.username }}
            {{- if .Values.chats.db.password.secret.enabled }}
            - name: CHATS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.chats.db.password.secret.name }}"
                  key: "{{ .Values.chats.db.password.secret.key }}"
            {{- else }}
            - name: CHATS_DB_PASSWORD
              value: "{{ .Values.chats.db.password.raw }}"
            {{- end }}
            - name: CHATS_DB_TABLE_NAME
              value: {{ .Values.chats.db.table.name }}
            - name: CHATS_DB_TLS_ENABLED
              value: "{{ .Values.chats.db.tls.enabled }}"
            - name: CHATS_DB_TLS_INSECURE
              value: "{{ .Values.chats.db.tls.insecure }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
            - name: PAYMENT_BACKOFF_FACTOR
              value: "{{ .Values.payment.backoff.factor }}"
            - name: PAYMENT_BACKOFF_INIT
              value: "{{ .Values.payment.backoff.init }}"
            - name: PAYMENT_BACKOFF_LIMIT_TOTAL
              value: "{{ .Values.payment.backoff.limitTotal }}"
            - name: PAYMENT_CURRENCY_CODE
              value: "{{ .Values.payment.currency.code }}"
            - name: PAYMENT_CURRENCY_SUB_FACTOR
              value: "{{ .Values.payment.currency.subFactor }}"
            - name: PAYMENT_DONATION_CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: bot-telegram-tokens
                  key: donation
            - name: PAYMENT_PRE_CHECKOUT_TIMEOUT
              value: "{{ .Values.payment.preCheckout.timeout }}"
            - name: PAYMENT_PRICE_MESSAGE_PUBLISHING_DAILY_LIMIT
              value: "{{ .Values.payment.price.messagePublishing.dailyLimit }}"
            - name: PAYMENT_PRICE_MESSAGE_PUBLISHING_EXTRA
              value: "{{ .Values.payment.price.messagePublishing.extra }}"
            - name: PAYMENT_PRICE_SUBSCRIPTION_COUNT_LIMIT
              value: "{{ .Values.payment.price.subscription.countLimit }}"
            - name: PAYMENT_PRICE_SUBSCRIPTION_EXTENSION
              value: "{{ .Values.payment.price.subscription.extension }}"
            - name: PAYMENT_PROVIDER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ include "bot-telegram.fullname" . }}-tokens"
                  key: payment
            - name: REPLICA_RANGE
              value: "{{ .Values.replicaCount }}"
            - name: REPLICA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: server-cert
              mountPath: "/etc/server-cert"
              readOnly: true
      volumes:
        - name: server-cert
          secret:
            secretName: secret-bot-telegram-tls-server
            items:
              - key: tls.crt
                path: tls.crt
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "bot-telegram.name" . }}
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
